### ISSUE TITLE
"enableAutoDocumentation" behavior expected

### ISSUE THREAD

**Issue by VincentClair** [adlarge/fixtures-documentation-bundle#21]
When enableAutoDocumentation option set to true, I expect to not fullfill configEntities with all entities and their properties. Its really annoying ;) but the bundle to get all properties and autolink to linked entities.

Hope you could simplify it :)

**Comment by bluepioupiou** [comment]
maybe not the default behavior ? I'm afraid it can be a lot of properties and links. Do we do that if there is no config entities ? Do we do that to (all properties and links) if the config of the entity is empty ? Or do we set a keyword to obtain that ?

**Comment by bluepioupiou** [comment]
And the 1 million dollars question being : how do you know the properties of the object on a "all private" properties class ?

**Comment by VincentClair** [comment]
I've just seen your commits on this request.
Please look at the https://github.com/adlarge/fixtures-documentation-bundle/pull/25 as it could be ore strait forward but maybe mixed some concepts.
